repos:
-   repo: meta
    hooks:
      - id: check-hooks-apply
-   repo: local
    hooks:
      - id: refactor
        name: refactor
        language: system
        entry: refactor
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-vcs-permalinks
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
    -   id: setup-cfg-fmt
        args:
        -    --include-version-classifiers
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.982'
    hooks:
      -  id: mypy
-   repo: https://github.com/hakancelikdev/unimport
    rev: 0.12.1
    hooks:
      - id: unimport
        args:
        -   --config
        -   setup.cfg
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    -   id: codespell
